### ISSUE TITLE
Hangs on "Loading games"

### ISSUE THREAD

**Issue by Pherrera0** [hexdump2002/game-miner-public#88]
First off, thank you for making this app. I want to move away from using Steam Rom Manager for handling PC games, and this application seems to do exactly what I need. My issue is similar to #86 . The application starts but hangs on "Loading games". I'm running the latest Bazzite (3.7.0, based of Fedora 41) on the Legion Go. Steam version is 1733265492 from the stable channel.

Here is the console output: 
```
deck@bazzite:~/AppImages$ ./game_miner.appimage
Gtk-Message: 10:09:13.796: Failed to load module "canberra-gtk-module"
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Character 123 is not found at position 20
#0      TxtVdfFile.peek (package:game_miner/logic/io/text_vdf_file.dart:117)
#1      TxtVdfFile._readObject (package:game_miner/logic/io/text_vdf_file.dart:76)
#2      TxtVdfFile.read (package:game_miner/logic/io/text_vdf_file.dart:38)
<asynchronous suspension>
#3      CompatToolsDataProvider.loadExternalCompatTools (package:game_miner/data/data_providers/compat_tools_data_provider.dart:43)
<asynchronous suspension>
#4      CompatToolsRepository.loadCompatTools (package:game_miner/data/repositories/compat_tools_repository.dart:16)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Character 123 is not found at position 20
#0      TxtVdfFile.peek (package:game_miner/logic/io/text_vdf_file.dart:117)
#1      TxtVdfFile._readObject (package:game_miner/logic/io/text_vdf_file.dart:76)
#2      TxtVdfFile.read (package:game_miner/logic/io/text_vdf_file.dart:38)
<asynchronous suspension>
#3      CompatToolsDataProvider.loadExternalCompatTools (package:game_miner/data/data_providers/compat_tools_data_provider.dart:43)
<asynchronous suspension>
#4      CompatToolsRepository.loadCompatTools (package:game_miner/data/repositories/compat_tools_repository.dart:16)
<asynchronous suspension>
#5      GameMgrCubit._loadData (package:game_miner/logic/blocs/game_mgr_cubit.dart:157)
<asynchronous suspension>


(GameMiner:156925): Gdk-WARNING **: 10:09:23.713: ../gdk/wayland/gdkselection-wayland.c:283: error reading selection buffer: Operation was cancelled
```
I tried renaming shortcuts.vdf and relaunched steam to test if it was shortcuts.vdf itself that was corrupted; no change. 

Thanks

**Comment by hexdump2002** [comment]
I'm on it... haven't had time to fix it after Valve havok with Steam OS.

On the other hand I'm adding some QOL for new users or users not experienced with terminal to let them show errors without having to do any terminal manoeuvre. It is very ugly, but it does the job :).

![Image](https://github.com/user-attachments/assets/71a36ea6-7a97-4a82-bb79-7c82ee135f91)

Expect a release along this week or next depending of the spare time I have.

**Comment by hexdump2002** [comment]
FIxed!
